"""Seed data script for the Prompt Engineering LMS."""
import logging

from sqlalchemy.orm import Session

from app.db.database import SessionLocal, engine, Base
from app.models.models import (
    User,
    RoleEnum,
    Basket,
    Module,
    Lesson,
    Exercise,
    Quiz,
    Lab,
    Assignment,
    LessonSection,
    SectionQuiz,
)
from app.services.auth import hash_password

logger = logging.getLogger(__name__)


def seed_database():
    """Populate the database with initial seed data."""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # Check if data already exists
        if db.query(User).first():
            logger.info("Database already seeded. Skipping.")
            return

        logger.info("Seeding database...")

        # ── Create Admin User ─────────────────────────────────────────────
        admin = User(
            email="admin@prompteng.edu",
            username="admin",
            hashed_password=hash_password("admin123"),
            full_name="Platform Admin",
            role=RoleEnum.ADMIN,
        )
        db.add(admin)

        # ── Create Demo Student ───────────────────────────────────────────
        student = User(
            email="student@prompteng.edu",
            username="student",
            hashed_password=hash_password("student123"),
            full_name="Demo Student",
            role=RoleEnum.STUDENT,
        )
        db.add(student)
        db.flush()

        # ── Create Baskets ───────────────────────────────────────────────
        basket1 = Basket(
            title="Basic Prompt Engineering",
            description="Foundation course covering the basics of prompt engineering with LLMs. Learn how to write effective prompts, understand LLM behavior, and apply fundamental techniques.",
            credits=8,
            order=1,
        )
        basket2 = Basket(
            title="Intermediate Prompt Engineering",
            description="Advanced techniques including chain-of-thought, multi-step prompting, and domain-specific prompt design patterns.",
            credits=8,
            order=2,
        )
        basket3 = Basket(
            title="Advanced Prompt Engineering",
            description="Expert-level prompt engineering covering autonomous agents, complex workflow design, and production-grade prompt systems.",
            credits=8,
            order=3,
        )
        db.add_all([basket1, basket2, basket3])
        db.flush()

        # ── Basket 1: Basic Prompt Engineering ────────────────────────────

        # Module 1: Introduction to LLMs
        mod1 = Module(
            basket_id=basket1.id,
            title="Introduction to LLMs",
            description="Understand the fundamentals of Large Language Models and how they process prompts.",
            order=1,
        )
        # Module 2: Prompt Fundamentals
        mod2 = Module(
            basket_id=basket1.id,
            title="Prompt Fundamentals",
            description="Learn the core principles of writing effective prompts for AI systems.",
            order=2,
        )
        # Module 3: Few-shot Prompting
        mod3 = Module(
            basket_id=basket1.id,
            title="Few-shot Prompting",
            description="Master the technique of providing examples to guide AI responses.",
            order=3,
        )
        # Module 4: Prompt Optimization
        mod4 = Module(
            basket_id=basket1.id,
            title="Prompt Optimization",
            description="Learn systematic approaches to improve and optimize your prompts.",
            order=4,
        )
        db.add_all([mod1, mod2, mod3, mod4])
        db.flush()

        # ── Lessons for Module 1: Introduction to LLMs ───────────────────
        lessons_mod1 = [
            Lesson(
                module_id=mod1.id,
                title="What are Large Language Models?",
                content=(
                    "Large Language Models (LLMs) are AI systems trained on vast amounts of text data. "
                    "They can understand and generate human-like text based on the input they receive.\n\n"
                    "Key concepts:\n"
                    "- **Tokens**: LLMs process text as tokens (words or word pieces)\n"
                    "- **Context Window**: The amount of text an LLM can consider at once\n"
                    "- **Temperature**: Controls randomness in responses\n"
                    "- **Completion**: The text generated by the model"
                ),
                transcript="In this lesson, we explore what large language models are and how they work...",
                notes="LLMs are trained on billions of parameters using transformer architecture.",
                video_url="https://assets.mixkit.co/videos/99786/99786-720.mp4",
                order=1,
                duration_minutes=15,
            ),
            Lesson(
                module_id=mod1.id,
                title="How LLMs Process Prompts",
                content=(
                    "Understanding how LLMs process your input is crucial for effective prompt engineering.\n\n"
                    "The processing pipeline:\n"
                    "1. **Tokenization**: Your text is split into tokens\n"
                    "2. **Encoding**: Tokens are converted to numerical representations\n"
                    "3. **Attention**: The model weighs the importance of each token\n"
                    "4. **Generation**: Output tokens are produced one at a time\n\n"
                    "This is why prompt structure matters - the model's attention mechanism "
                    "determines what parts of your prompt influence the output most."
                ),
                transcript="Let's dive into the internal workings of how an LLM processes your prompts...",
                notes="Attention mechanism is the key innovation behind transformer models.",
                video_url="https://assets.mixkit.co/videos/46635/46635-720.mp4",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod1.id,
                title="Common LLM Capabilities and Limitations",
                content=(
                    "LLMs have impressive capabilities but also important limitations.\n\n"
                    "**Capabilities:**\n"
                    "- Text generation and completion\n"
                    "- Summarization and extraction\n"
                    "- Translation and paraphrasing\n"
                    "- Code generation\n"
                    "- Reasoning and analysis\n\n"
                    "**Limitations:**\n"
                    "- Can hallucinate (generate false information)\n"
                    "- Knowledge cutoff dates\n"
                    "- Token limit constraints\n"
                    "- May not follow complex instructions consistently"
                ),
                transcript="In this lesson, we'll explore what LLMs can and cannot do...",
                notes="Always verify critical information from LLM outputs.",
                video_url="https://assets.mixkit.co/videos/50748/50748-720.mp4",
                order=3,
                duration_minutes=18,
            ),
        ]
        db.add_all(lessons_mod1)
        db.flush()

        # ── Lessons for Module 2: Prompt Fundamentals ─────────────────────
        lessons_mod2 = [
            Lesson(
                module_id=mod2.id,
                title="Anatomy of a Good Prompt",
                content=(
                    "A well-structured prompt has several key components:\n\n"
                    "1. **Role/Context**: Define who the AI should be\n"
                    "2. **Task**: Clearly state what you want done\n"
                    "3. **Constraints**: Set boundaries and requirements\n"
                    "4. **Output Format**: Specify how the response should be structured\n"
                    "5. **Examples**: Provide sample inputs and outputs\n\n"
                    "Example:\n"
                    "```\n"
                    "You are a professional copywriter.\n"
                    "Write a product description for a wireless mouse.\n"
                    "Keep it under 100 words.\n"
                    "Use bullet points for features.\n"
                    "```"
                ),
                transcript="Let's learn the fundamental building blocks of an effective prompt...",
                notes="Always start with the role and end with the desired output format.",
                video_url="https://assets.mixkit.co/videos/9757/9757-720.mp4",
                order=1,
                duration_minutes=25,
            ),
            Lesson(
                module_id=mod2.id,
                title="Zero-shot Prompting",
                content=(
                    "Zero-shot prompting is when you ask the AI to perform a task without providing examples.\n\n"
                    "This relies on the model's pre-trained knowledge.\n\n"
                    "**Example:**\n"
                    "```\n"
                    "Classify the following text as positive, negative, or neutral:\n"
                    "'The weather today is absolutely beautiful!'\n"
                    "```\n\n"
                    "**Tips for better zero-shot prompts:**\n"
                    "- Be as specific as possible\n"
                    "- Use clear, unambiguous language\n"
                    "- Specify the exact output format you want"
                ),
                transcript="Zero-shot prompting is the simplest form of prompt engineering...",
                notes="Zero-shot works best for simple, well-defined tasks.",
                video_url="https://assets.mixkit.co/videos/12748/12748-720.mp4",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod2.id,
                title="Instruction Clarity and Specificity",
                content=(
                    "The clarity of your instructions directly impacts the quality of AI output.\n\n"
                    "**Vague vs. Specific:**\n"
                    "- Vague: 'Tell me about Python'\n"
                    "- Specific: 'Explain the difference between lists and tuples in Python with code examples'\n\n"
                    "**Techniques for clarity:**\n"
                    "1. Use numbered steps for multi-part tasks\n"
                    "2. Define technical terms if needed\n"
                    "3. Specify the audience level\n"
                    "4. Set word/length constraints\n"
                    "5. Use delimiters to separate sections"
                ),
                transcript="Let's explore how to make your prompts crystal clear...",
                notes="Specificity reduces ambiguity and improves AI output quality.",
                video_url="https://assets.mixkit.co/videos/47051/47051-720.mp4",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod2)
        db.flush()

        # ── Lessons for Module 3: Few-shot Prompting ──────────────────────
        lessons_mod3 = [
            Lesson(
                module_id=mod3.id,
                title="Introduction to Few-shot Learning",
                content=(
                    "Few-shot prompting provides examples to guide the AI's behavior.\n\n"
                    "**Structure:**\n"
                    "```\n"
                    "Example 1:\n"
                    "Input: [example input]\n"
                    "Output: [example output]\n\n"
                    "Example 2:\n"
                    "Input: [example input]\n"
                    "Output: [example output]\n\n"
                    "Now do this:\n"
                    "Input: [your actual input]\n"
                    "Output:\n"
                    "```\n\n"
                    "Few-shot prompting is especially powerful for:\n"
                    "- Classification tasks\n"
                    "- Format standardization\n"
                    "- Domain-specific terminology"
                ),
                transcript="Few-shot learning is one of the most powerful techniques...",
                notes="Even 2-3 examples can dramatically improve output quality.",
                video_url="https://assets.mixkit.co/videos/23282/23282-720.mp4",
                order=1,
                duration_minutes=25,
            ),
            Lesson(
                module_id=mod3.id,
                title="Choosing Effective Examples",
                content=(
                    "The quality and diversity of your examples matters more than quantity.\n\n"
                    "**Guidelines:**\n"
                    "1. Choose diverse examples that cover edge cases\n"
                    "2. Keep examples consistent in format\n"
                    "3. Include both simple and complex cases\n"
                    "4. Make sure examples are correct\n"
                    "5. Order examples from simple to complex\n\n"
                    "**Common mistakes:**\n"
                    "- Using too many similar examples\n"
                    "- Providing incorrect examples\n"
                    "- Inconsistent formatting between examples"
                ),
                transcript="Selecting the right examples is crucial for few-shot prompting...",
                notes="Quality over quantity - 3 diverse examples beat 10 similar ones.",
                video_url="https://assets.mixkit.co/videos/41638/41638-720.mp4",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod3.id,
                title="Few-shot Patterns for Different Tasks",
                content=(
                    "Different tasks benefit from different few-shot patterns.\n\n"
                    "**Classification Pattern:**\n"
                    "Text: 'Great product!' -> Sentiment: Positive\n"
                    "Text: 'Terrible service' -> Sentiment: Negative\n\n"
                    "**Extraction Pattern:**\n"
                    "Text: 'John is 30 years old' -> {name: 'John', age: 30}\n\n"
                    "**Transformation Pattern:**\n"
                    "Formal: 'I would like to...' -> Casual: 'I wanna...'\n\n"
                    "**Generation Pattern:**\n"
                    "Topic: 'AI' -> Title: '10 Ways AI is Changing Healthcare'"
                ),
                transcript="Let's explore specific few-shot patterns for common tasks...",
                notes="Match your example pattern to your specific task type.",
                video_url="https://assets.mixkit.co/videos/31771/31771-720.mp4",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod3)
        db.flush()

        # ── Lessons for Module 4: Prompt Optimization ─────────────────────
        lessons_mod4 = [
            Lesson(
                module_id=mod4.id,
                title="Iterative Prompt Refinement",
                content=(
                    "Prompt optimization is an iterative process.\n\n"
                    "**The Optimization Loop:**\n"
                    "1. Write initial prompt\n"
                    "2. Test with various inputs\n"
                    "3. Analyze output quality\n"
                    "4. Identify weaknesses\n"
                    "5. Refine the prompt\n"
                    "6. Repeat\n\n"
                    "**Metrics to track:**\n"
                    "- Accuracy of responses\n"
                    "- Consistency across inputs\n"
                    "- Adherence to format\n"
                    "- Response relevance"
                ),
                transcript="Let's learn how to systematically improve prompts...",
                notes="Keep a log of prompt versions and their results.",
                video_url="https://assets.mixkit.co/videos/221/221-720.mp4",
                order=1,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod4.id,
                title="Temperature and Parameter Tuning",
                content=(
                    "Model parameters significantly affect output quality.\n\n"
                    "**Temperature (0.0 - 2.0):**\n"
                    "- 0.0: Deterministic, focused responses\n"
                    "- 0.7: Balanced creativity and accuracy\n"
                    "- 1.5+: Highly creative, less predictable\n\n"
                    "**Other parameters:**\n"
                    "- **Top-p**: Controls diversity of token selection\n"
                    "- **Max tokens**: Limits response length\n"
                    "- **Frequency penalty**: Reduces repetition\n"
                    "- **Presence penalty**: Encourages topic diversity"
                ),
                transcript="Understanding model parameters helps you fine-tune outputs...",
                notes="Start with temperature 0.7 and adjust based on task needs.",
                video_url="https://assets.mixkit.co/videos/43527/43527-720.mp4",
                order=2,
                duration_minutes=18,
            ),
            Lesson(
                module_id=mod4.id,
                title="Common Prompt Anti-patterns",
                content=(
                    "Avoid these common mistakes in prompt engineering.\n\n"
                    "**Anti-patterns:**\n"
                    "1. **Vague instructions**: 'Do something interesting with this data'\n"
                    "2. **Conflicting requirements**: 'Be concise but detailed'\n"
                    "3. **Missing context**: Assuming the AI knows your domain\n"
                    "4. **Over-constraining**: Too many rules that conflict\n"
                    "5. **Prompt injection vulnerability**: Not sanitizing user inputs\n\n"
                    "**Best practices:**\n"
                    "- Test prompts with edge cases\n"
                    "- Version control your prompts\n"
                    "- Document what works and what doesn't"
                ),
                transcript="Let's identify and fix common prompt engineering mistakes...",
                notes="The best prompt engineers learn from their failures.",
                video_url="https://assets.mixkit.co/videos/51214/51214-720.mp4",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod4)
        db.flush()

        # ── Create Exercises ──────────────────────────────────────────────
        exercises = [
            Exercise(
                lesson_id=lessons_mod2[0].id,
                title="Write a Role-Based Prompt",
                description="Create a prompt that assigns a specific role to the AI and asks it to complete a task.",
                prompt_template="You are a [role]. [task]. [constraints]. [output format].",
                expected_output="A well-structured prompt with role, task, constraints, and output format.",
                hints="Think about what expert would be best suited for the task.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod2[1].id,
                title="Zero-shot Classification",
                description="Write a zero-shot prompt to classify customer reviews as positive, negative, or neutral.",
                prompt_template="Classify the following customer review as positive, negative, or neutral: '[review text]'",
                expected_output="The classification label with a brief explanation.",
                hints="Be specific about the classification categories and output format.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod3[0].id,
                title="Few-shot Sentiment Analysis",
                description="Create a few-shot prompt for sentiment analysis with at least 3 examples.",
                prompt_template="Classify the sentiment:\nExample 1: 'Love it!' -> Positive\nExample 2: 'Worst ever' -> Negative\nNow classify: '[text]'",
                expected_output="Correct sentiment classification following the example format.",
                hints="Use diverse examples covering different expressions.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod4[0].id,
                title="Prompt Iteration Challenge",
                description="Start with a basic prompt and iterate 3 times to improve it, documenting changes.",
                prompt_template="Version 1: [basic prompt]\nVersion 2: [improved prompt]\nVersion 3: [optimized prompt]",
                expected_output="Three versions showing clear improvement in clarity and specificity.",
                hints="Focus on one improvement dimension per iteration.",
                order=1,
            ),
        ]
        db.add_all(exercises)

        # ── Create Quizzes ────────────────────────────────────────────────
        quizzes = [
            Quiz(
                lesson_id=lessons_mod1[0].id,
                question="What is the primary input to a Large Language Model?",
                options=["Images", "Tokens (text)", "Audio files", "Binary data"],
                correct_answer="Tokens (text)",
                explanation="LLMs process text as tokens, which are words or sub-word pieces.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod1[1].id,
                question="What mechanism allows LLMs to weigh the importance of different tokens?",
                options=["Convolution", "Attention", "Pooling", "Dropout"],
                correct_answer="Attention",
                explanation="The attention mechanism is the key innovation in transformer models.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod2[0].id,
                question="Which component should typically come FIRST in a well-structured prompt?",
                options=["Output format", "Examples", "Role/Context", "Constraints"],
                correct_answer="Role/Context",
                explanation="Setting the role/context first helps frame the entire interaction.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod3[0].id,
                question="How many examples are typically needed for effective few-shot prompting?",
                options=["1", "2-5", "10-20", "50+"],
                correct_answer="2-5",
                explanation="Usually 2-5 well-chosen examples are sufficient for most tasks.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod4[1].id,
                question="What temperature value would you use for a factual Q&A task?",
                options=["0.0 - 0.3", "0.5 - 0.7", "1.0 - 1.5", "2.0"],
                correct_answer="0.0 - 0.3",
                explanation="Low temperature produces more deterministic, focused responses suitable for factual tasks.",
                order=1,
            ),
        ]
        db.add_all(quizzes)

        # ── Create Labs ───────────────────────────────────────────────────
        labs = [
            Lab(
                module_id=mod1.id,
                title="Build a Chatbot Prompt",
                description="Design a system prompt for a customer service chatbot.",
                instructions=(
                    "1. Define the chatbot's personality and role\n"
                    "2. Set boundaries for what the chatbot can and cannot discuss\n"
                    "3. Include example interactions\n"
                    "4. Add safety guidelines\n"
                    "5. Test with various customer queries"
                ),
                starter_prompt="You are a helpful customer service assistant for [company]...",
                expected_output="A complete system prompt that handles various customer scenarios.",
                max_score=100,
            ),
            Lab(
                module_id=mod2.id,
                title="Structured JSON Extraction",
                description="Create a prompt that extracts structured data from unstructured text.",
                instructions=(
                    "1. Write a prompt that takes a paragraph of text\n"
                    "2. Extract key entities (names, dates, locations, amounts)\n"
                    "3. Output in valid JSON format\n"
                    "4. Handle edge cases (missing data, ambiguous references)\n"
                    "5. Include few-shot examples"
                ),
                starter_prompt="Extract the following information from the text and return as JSON...",
                expected_output="A JSON extraction prompt that works reliably across different inputs.",
                max_score=100,
            ),
            Lab(
                module_id=mod3.id,
                title="Multi-step Prompt Chain",
                description="Design a chain of prompts that work together to solve a complex task.",
                instructions=(
                    "1. Break down a complex task into 3-4 steps\n"
                    "2. Design a prompt for each step\n"
                    "3. Define how output from one step feeds into the next\n"
                    "4. Handle errors between steps\n"
                    "5. Test the complete chain"
                ),
                starter_prompt="Step 1: Analyze the text...\nStep 2: Based on the analysis...",
                expected_output="A working chain of prompts that solves a multi-step problem.",
                max_score=100,
            ),
            Lab(
                module_id=mod4.id,
                title="AI Assistant Workflow",
                description="Build a complete AI assistant workflow for a specific domain.",
                instructions=(
                    "1. Choose a domain (e.g., healthcare, legal, education)\n"
                    "2. Design the system prompt\n"
                    "3. Create prompt templates for common tasks\n"
                    "4. Implement safety and guardrails\n"
                    "5. Create a testing suite with diverse inputs\n"
                    "6. Document the workflow"
                ),
                starter_prompt="You are an AI assistant specializing in [domain]...",
                expected_output="A production-ready AI assistant workflow with documentation.",
                max_score=100,
            ),
        ]
        db.add_all(labs)

        # ── Create Assignments ────────────────────────────────────────────
        assignments = [
            Assignment(
                module_id=mod1.id,
                title="LLM Exploration Report",
                description="Explore different LLMs and write a comparison report.",
                instructions=(
                    "1. Test the same prompt on at least 2 different LLMs\n"
                    "2. Compare the responses for quality, accuracy, and style\n"
                    "3. Document your findings with examples\n"
                    "4. Recommend which LLM works best for specific task types"
                ),
                rubric={
                    "prompt_quality": 25,
                    "comparison_depth": 25,
                    "examples": 25,
                    "recommendations": 25,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod2.id,
                title="Prompt Design Portfolio",
                description="Create a portfolio of 5 well-designed prompts for different tasks.",
                instructions=(
                    "1. Write prompts for: summarization, extraction, classification, generation, and analysis\n"
                    "2. Each prompt must include role, task, constraints, and output format\n"
                    "3. Test each prompt and include the AI output\n"
                    "4. Write a brief explanation of your design choices"
                ),
                rubric={
                    "prompt_variety": 20,
                    "prompt_quality": 30,
                    "testing": 25,
                    "explanation": 25,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod3.id,
                title="Few-shot Prompting Challenge",
                description="Solve 3 complex tasks using few-shot prompting techniques.",
                instructions=(
                    "1. Design few-shot prompts for:\n"
                    "   a. Named Entity Recognition\n"
                    "   b. Text style transfer\n"
                    "   c. Data format conversion\n"
                    "2. Include 3-5 examples per prompt\n"
                    "3. Test with at least 5 different inputs each\n"
                    "4. Report accuracy and analyze failures"
                ),
                rubric={
                    "example_quality": 30,
                    "prompt_design": 25,
                    "testing_thoroughness": 25,
                    "analysis": 20,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod4.id,
                title="Prompt Optimization Case Study",
                description="Document the optimization journey of a complex prompt.",
                instructions=(
                    "1. Choose a complex real-world task\n"
                    "2. Start with a naive prompt (Version 1)\n"
                    "3. Iterate at least 5 times\n"
                    "4. Document each version with:\n"
                    "   - The prompt text\n"
                    "   - What changed and why\n"
                    "   - Test results\n"
                    "   - Score improvements\n"
                    "5. Write a conclusion about optimization strategies"
                ),
                rubric={
                    "iteration_quality": 25,
                    "documentation": 25,
                    "improvement_shown": 25,
                    "conclusion": 25,
                },
                max_score=100,
                due_hours=336,
            ),
        ]
        db.add_all(assignments)

        # ── Create Lesson Sections & Section Quizzes ──────────────────────
        all_lessons = lessons_mod1 + lessons_mod2 + lessons_mod3 + lessons_mod4
        _seed_lesson_sections(db, all_lessons)

        db.commit()
        logger.info("Database seeded successfully!")

    except Exception as e:
        db.rollback()
        logger.error(f"Seeding failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()


def _seed_lesson_sections(db: Session, lessons: list):
    """Create 3 sections with 4 MCQs each for all lessons."""
    _SECTIONS_DATA = [
        # Lesson 1: What are Large Language Models?
        {
            "sections": [
                ("Introduction to LLMs", "Large Language Models are neural networks trained on massive text datasets. They learn patterns in language and can generate human-like text based on prompts."),
                ("Key LLM Concepts", "Understanding tokens, context windows, and temperature is essential. Tokens are the building blocks, context window is the memory limit, and temperature controls creativity vs accuracy."),
                ("How LLMs Learn", "LLMs use transformer architecture with billions of parameters. They are trained through self-supervised learning on diverse text to predict the next token."),
            ],
            "quizzes": [
                [
                    ("What are Large Language Models primarily trained on?", ["Images", "Text data", "Audio files", "Structured databases"], "Text data", "LLMs are trained on vast amounts of text data from books, websites, and documents."),
                    ("What type of neural network architecture do modern LLMs use?", ["Convolutional", "Recurrent", "Transformer", "Feedforward"], "Transformer", "Transformer architecture is the foundation of models like GPT and BERT."),
                    ("What is the primary output of an LLM?", ["Classifications", "Generated text", "Numerical predictions", "Image captions"], "Generated text", "LLMs generate text completions based on input prompts."),
                    ("How do LLMs process input text?", ["Character by character", "Word by word", "As tokens", "As sentences"], "As tokens", "Text is tokenized into smaller units (tokens) for processing."),
                ],
                [
                    ("What is a token in the context of LLMs?", ["A word", "A word or sub-word piece", "A sentence", "A paragraph"], "A word or sub-word piece", "Tokens can be whole words or parts of words, depending on the tokenizer."),
                    ("What does the context window represent?", ["Screen size", "Amount of text the model can consider", "Training data size", "Model parameters"], "Amount of text the model can consider", "Context window is the maximum amount of text (in tokens) the model can process at once."),
                    ("What does temperature control in LLM generation?", ["Processing speed", "Randomness and creativity", "Token limit", "Training quality"], "Randomness and creativity", "Higher temperature increases randomness; lower temperature makes output more deterministic."),
                    ("What is a completion in LLM terminology?", ["Finished training", "Generated output text", "Full context window", "Model accuracy"], "Generated output text", "A completion is the text generated by the model in response to a prompt."),
                ],
                [
                    ("What type of learning approach is used to train LLMs?", ["Supervised", "Self-supervised", "Reinforcement", "Transfer"], "Self-supervised", "LLMs use self-supervised learning by predicting masked or next tokens from unlabeled text data."),
                    ("Approximately how many parameters do large modern LLMs have?", ["Millions", "Billions", "Thousands", "Hundreds"], "Billions", "Modern LLMs like GPT-3 have hundreds of billions of parameters."),
                    ("What is the key innovation in transformer models?", ["Convolution", "Attention mechanism", "Pooling layers", "Dropout"], "Attention mechanism", "The attention mechanism allows models to weigh the importance of different tokens in the input."),
                    ("What does pre-training an LLM involve?", ["Fine-tuning on specific tasks", "Learning from massive unlabeled text", "Human feedback loops", "Supervised classification"], "Learning from massive unlabeled text", "Pre-training exposes the model to diverse text to learn general language patterns."),
                ],
            ],
        },
        # Lesson 2: How LLMs Process Prompts
        {
            "sections": [
                ("Tokenization Process", "Your input text is split into tokens using a tokenizer. Each token is assigned a unique ID and converted to a numerical representation (embedding vector)."),
                ("Attention and Processing", "The model uses attention mechanisms to weigh the importance of each token. Tokens are processed through multiple transformer layers to understand context and relationships."),
                ("Generation Pipeline", "Output tokens are generated one at a time. The model predicts the most likely next token, adds it to the sequence, and repeats until completion."),
            ],
            "quizzes": [
                [
                    ("What is the first step in processing a prompt?", ["Attention", "Tokenization", "Generation", "Embedding"], "Tokenization", "Text must first be split into tokens before any processing."),
                    ("What is an embedding vector?", ["Token ID", "Numerical representation of a token", "Attention weight", "Output prediction"], "Numerical representation of a token", "Embeddings capture semantic meaning of tokens in vector space."),
                    ("Why is tokenization necessary?", ["To save memory", "To convert text to numerical format", "To compress data", "To filter noise"], "To convert text to numerical format", "Neural networks operate on numbers, not raw text."),
                    ("What determines how text is split into tokens?", ["Random splitting", "The tokenizer algorithm", "User preference", "Context window"], "The tokenizer algorithm", "Different tokenizers use different strategies (BPE, WordPiece, etc.)."),
                ],
                [
                    ("What does the attention mechanism do?", ["Speeds up processing", "Weighs importance of tokens", "Generates output", "Compresses input"], "Weighs importance of tokens", "Attention helps the model focus on relevant parts of the input."),
                    ("How many transformer layers do large LLMs typically have?", ["1-5", "10-20", "50-100+", "500+"], "50-100+", "Models like GPT-3 have 96 transformer layers."),
                    ("What type of attention do transformers use?", ["Local attention", "Self-attention", "Cross attention", "Sparse attention"], "Self-attention", "Self-attention allows each token to attend to all other tokens in the sequence."),
                    ("Why does prompt structure matter?", ["It does not matter", "Attention weighs different parts differently", "To save tokens", "For readability only"], "Attention weighs different parts differently", "The attention patterns are influenced by how the prompt is structured."),
                ],
                [
                    ("How does an LLM generate output?", ["All at once", "One token at a time", "By templates", "Through retrieval"], "One token at a time", "Auto-regressive generation produces one token per forward pass."),
                    ("What determines which token is generated next?", ["Random selection", "Probability distribution over vocabulary", "User input", "Fixed rules"], "Probability distribution over vocabulary", "The model outputs probabilities for each possible next token."),
                    ("Can you change already-generated tokens?", ["Yes easily", "No, generation is sequential", "Only with special models", "Yes but slowly"], "No, generation is sequential", "Once a token is generated, it becomes part of the input for the next token."),
                    ("What stops the generation process?", ["Max tokens reached or end token", "User interruption only", "Fixed time limit", "Random stopping"], "Max tokens reached or end token", "Generation stops when hitting the token limit or producing an end-of-sequence token."),
                ],
            ],
        },
        # Lesson 3: Common LLM Capabilities and Limitations
        {
            "sections": [
                ("Core Capabilities", "LLMs excel at text generation, summarization, translation, code generation, and reasoning. They can understand context and follow complex instructions."),
                ("Key Limitations", "LLMs can hallucinate (make up false information), have knowledge cutoff dates, and may not follow very complex or contradictory instructions consistently."),
                ("Best Practices", "Always verify critical information from LLM outputs. Use LLMs for drafting and ideation, but apply human judgment for accuracy and ethics."),
            ],
            "quizzes": [
                [
                    ("Which task are LLMs particularly good at?", ["Image recognition", "Text summarization", "Video editing", "Database queries"], "Text summarization", "LLMs excel at understanding and condensing text."),
                    ("Can LLMs generate code?", ["No", "Yes, across many programming languages", "Only in Python", "Only simple scripts"], "Yes, across many programming languages", "Modern LLMs can generate code in Python, JavaScript, Java, and more."),
                    ("What type of reasoning can LLMs perform?", ["None", "Logical reasoning and analysis", "Mathematical proofs only", "Physical reasoning only"], "Logical reasoning and analysis", "LLMs can perform multi-step reasoning when prompted correctly."),
                    ("Are LLMs good at following instructions?", ["Never", "Yes, when instructions are clear", "Only simple instructions", "Only with fine-tuning"], "Yes, when instructions are clear", "LLMs are trained to follow instructions, especially with clear prompts."),
                ],
                [
                    ("What does hallucination mean for LLMs?", ["Creative writing", "Generating false or made-up information", "Visual outputs", "Model errors"], "Generating false or made-up information", "LLMs may confidently state incorrect facts that sound plausible."),
                    ("What is a knowledge cutoff date?", ["When training ended", "Expiration date", "Release date", "Update schedule"], "When training ended", "LLMs lack knowledge of events after their training data was collected."),
                    ("How do LLMs handle contradictory instructions?", ["Always follow the first", "May become confused or inconsistent", "Always follow the last", "Reject the prompt"], "May become confused or inconsistent", "Conflicting requirements can lead to unpredictable behavior."),
                    ("What is the token limit constraint?", ["Cost per token", "Maximum input+output length", "Training limit", "Speed limit"], "Maximum input+output length", "Each model has a maximum number of tokens it can process."),
                ],
                [
                    ("Should you trust LLM outputs without verification?", ["Yes always", "No, always verify critical information", "Only for simple tasks", "Only from large models"], "No, always verify critical information", "LLMs can hallucinate, so verification is essential for important use cases."),
                    ("What is a good use case for LLMs?", ["Legal decisions", "Medical diagnosis", "Brainstorming and drafting", "Financial trading"], "Brainstorming and drafting", "LLMs are excellent for generating ideas and initial drafts that humans can refine."),
                    ("When should human judgment be applied?", ["Never needed", "For accuracy, ethics, and critical decisions", "Only for technical content", "Only for creative writing"], "For accuracy, ethics, and critical decisions", "Humans should review LLM outputs for correctness and ethical considerations."),
                    ("How should you handle LLM-generated code?", ["Deploy immediately", "Review and test before use", "Ignore security", "Trust blindly"], "Review and test before use", "Generated code should be reviewed for correctness, security, and best practices."),
                ],
            ],
        },
        # Lesson 4: Anatomy of a Good Prompt
        {
            "sections": [
                ("Role and Context", "Defining the role helps the AI understand the perspective and expertise level to adopt. Context provides background information needed for the task."),
                ("Task and Constraints", "Clear task description states what you want done. Constraints set boundaries on length, format, style, and content."),
                ("Output Format and Examples", "Specify how the response should be structured. Examples demonstrate the expected pattern and quality."),
            ],
            "quizzes": [
                [
                    ("What should come first in a prompt?", ["Examples", "Role and Context", "Output format", "Constraints"], "Role and Context", "Setting the role and context gives the AI a framework for its response."),
                    ("What does defining a role do?", ["Limits the model", "Sets perspective and expertise level", "Increases token usage", "Speeds up response"], "Sets perspective and expertise level", "Roles help the AI adopt the right tone and knowledge level."),
                    ("Why is context important in prompts?", ["To fill space", "Provides background for the task", "Required by API", "For formatting"], "Provides background for the task", "Context helps the model understand what you need."),
                    ("What is a system prompt?", ["Error message", "Role and behavior instructions", "Output format", "Training data"], "Role and behavior instructions", "System prompts set the overall behavior and role for the AI."),
                ],
                [
                    ("What are constraints in a prompt?", ["Boundaries and requirements", "Code blocks", "Variables", "APIs"], "Boundaries and requirements", "Constraints set limits on format, length, style, and content."),
                    ("Give an example of a good constraint.", ["Be creative", "Respond in exactly 3 bullet points", "Write something", "Do your best"], "Respond in exactly 3 bullet points", "Specific constraints give clear requirements."),
                    ("Why use constraints?", ["To confuse the model", "To get predictable, structured output", "To save money", "Required by law"], "To get predictable, structured output", "Constraints help ensure consistent output quality."),
                    ("What makes a task description clear?", ["Being vague", "Being specific about what you want", "Using jargon", "Being very long"], "Being specific about what you want", "Clear task descriptions reduce ambiguity in outputs."),
                ],
                [
                    ("Why provide output format examples?", ["To fill space", "To demonstrate expected pattern", "Required by model", "For testing"], "To demonstrate expected pattern", "Examples show the AI exactly what format you expect."),
                    ("What is a good output format specification?", ["Any format works", "JSON with specific fields", "Let the model decide", "Single word"], "JSON with specific fields", "Specific format specs ensure structured, parseable output."),
                    ("How many examples should you provide?", ["None", "1-3 representative examples", "As many as possible", "Exactly 10"], "1-3 representative examples", "A few good examples are usually sufficient to demonstrate the pattern."),
                    ("What is the RACE framework?", ["A speed test", "Role, Action, Context, Examples", "Random prompt generation", "AI rating system"], "Role, Action, Context, Examples", "RACE is a structured approach to writing effective prompts."),
                ],
            ],
        },
        # Lesson 5: Zero-shot Prompting
        {
            "sections": [
                ("Understanding Zero-shot", "Zero-shot prompting relies on the model pre-trained knowledge without providing examples. It is the simplest prompting technique."),
                ("Best Use Cases", "Works best for well-defined, simple tasks like classification, translation, or summarization where the task is clear."),
                ("Writing Effective Zero-shot Prompts", "Be specific, use clear language, specify output format, and avoid ambiguity in your instructions."),
            ],
            "quizzes": [
                [
                    ("What is zero-shot prompting?", ["No prompt given", "No examples provided", "No output expected", "No model used"], "No examples provided", "Zero-shot means the model works without demonstration examples."),
                    ("Why is zero-shot the simplest technique?", ["Less accurate", "No examples needed to write", "Always works", "Fastest processing"], "No examples needed to write", "You only need clear instructions without example input-output pairs."),
                    ("What does zero-shot rely on?", ["Training examples", "Pre-trained knowledge", "User expertise", "Fine-tuning"], "Pre-trained knowledge", "The model uses knowledge gained during pre-training."),
                    ("Is zero-shot always sufficient?", ["Yes", "No, complex tasks may need examples", "Only for English", "Only for GPT-4"], "No, complex tasks may need examples", "Some tasks benefit from few-shot examples for better results."),
                ],
                [
                    ("When does zero-shot work best?", ["Complex tasks", "Simple, well-defined tasks", "Creative tasks", "Mathematical proofs"], "Simple, well-defined tasks", "Clear, straightforward tasks work well without examples."),
                    ("Good zero-shot task example?", ["Writing a novel", "Classifying sentiment as positive or negative", "Complex data analysis", "Multi-step reasoning"], "Classifying sentiment as positive or negative", "Simple classification is ideal for zero-shot."),
                    ("Bad zero-shot task example?", ["Translation", "Following a very specific custom format", "Summarization", "Simple Q and A"], "Following a very specific custom format", "Custom formats usually need examples to demonstrate."),
                    ("What limits zero-shot effectiveness?", ["Model size", "Task ambiguity", "Internet speed", "Hardware"], "Task ambiguity", "Ambiguous tasks lead to unpredictable zero-shot results."),
                ],
                [
                    ("How to improve zero-shot prompts?", ["Add examples", "Be specific and clear", "Use complex language", "Keep it vague"], "Be specific and clear", "Clarity and specificity compensate for lack of examples."),
                    ("Should you specify output format in zero-shot?", ["No", "Yes, always helpful", "Only for JSON", "Only for code"], "Yes, always helpful", "Format specifications guide the model output structure."),
                    ("What word helps zero-shot classification?", ["Maybe", "Classify", "Possibly", "Consider"], "Classify", "Direct action verbs like classify give clear instructions."),
                    ("Best practice for zero-shot instructions?", ["Be vague", "Use one clear imperative sentence", "Write paragraphs", "Use questions only"], "Use one clear imperative sentence", "Direct, imperative instructions work best for zero-shot."),
                ],
            ],
        },
        # Lesson 6: Instruction Clarity and Specificity
        {
            "sections": [
                ("The Clarity Principle", "Clear instructions reduce ambiguity and improve output quality. Vague prompts lead to unpredictable results."),
                ("Specificity Techniques", "Use numbered steps, define technical terms, specify audience level, set word or length constraints, and use delimiters."),
                ("Testing and Refinement", "Test your prompt with various inputs to identify ambiguities. Refine based on what the model misunderstands."),
            ],
            "quizzes": [
                [
                    ("Why is clarity important in prompts?", ["Saves tokens", "Reduces ambiguity", "Faster processing", "Better grammar"], "Reduces ambiguity", "Clear prompts produce more predictable, useful outputs."),
                    ("What happens with vague prompts?", ["Better creativity", "Unpredictable results", "Faster responses", "Lower cost"], "Unpredictable results", "Vagueness gives the model too much freedom to interpret."),
                    ("Which is clearer?", ["Write about dogs", "Write a 200-word essay about golden retrievers for pet owners", "Dogs are nice", "Tell me about pets"], "Write a 200-word essay about golden retrievers for pet owners", "This prompt specifies length, topic, and audience."),
                    ("What does ambiguity in prompts cause?", ["Better output", "Inconsistent results across runs", "Faster processing", "Lower token usage"], "Inconsistent results across runs", "Ambiguous prompts can produce different outputs each time."),
                ],
                [
                    ("What helps make prompts more specific?", ["Vague terms", "Numbered steps and constraints", "Long paragraphs", "Technical jargon"], "Numbered steps and constraints", "Structure and constraints make expectations clear."),
                    ("What are delimiters used for?", ["Decoration", "Separating distinct parts of a prompt", "Counting tokens", "Formatting output"], "Separating distinct parts of a prompt", "Delimiters like triple quotes clearly mark different sections."),
                    ("Why specify audience level?", ["Not important", "Adjusts complexity and vocabulary", "Reduces cost", "Speeds processing"], "Adjusts complexity and vocabulary", "Audience level helps the model match tone and complexity."),
                    ("What is a good length constraint?", ["No limit", "Between 100-150 words", "As long as possible", "One word"], "Between 100-150 words", "Specific ranges give clear expectations for output length."),
                ],
                [
                    ("How to test prompt clarity?", ["Deploy immediately", "Test with various inputs", "Check grammar", "Count words"], "Test with various inputs", "Diverse test inputs reveal ambiguities in your prompt."),
                    ("What should you look for when testing?", ["Speed", "Inconsistencies in output", "Token count", "Model version"], "Inconsistencies in output", "Output inconsistencies signal unclear instructions."),
                    ("When to refine a prompt?", ["Never", "When outputs do not match expectations", "Every hour", "Only once"], "When outputs do not match expectations", "Refinement is needed when the model misinterprets instructions."),
                    ("What is iterative prompt design?", ["Writing once", "Repeatedly testing and improving prompts", "Using templates", "Copying prompts"], "Repeatedly testing and improving prompts", "Iteration improves prompt quality over time."),
                ],
            ],
        },
        # Lesson 7: Introduction to Few-shot Learning
        {
            "sections": [
                ("Few-shot Concept", "Few-shot prompting provides 2-5 examples to guide the AI behavior. Examples show the pattern you want the model to follow."),
                ("Structure of Few-shot Prompts", "Present examples in a consistent format: Example 1: Input then Output, Example 2: Input then Output, Now: Your input."),
                ("Power of Examples", "Examples are especially effective for classification, format standardization, and domain-specific terminology."),
            ],
            "quizzes": [
                [
                    ("How many examples does few-shot use?", ["0", "2-5", "50+", "Hundreds"], "2-5", "Few-shot typically uses a small number of carefully chosen examples."),
                    ("What is the purpose of few-shot examples?", ["Fill context window", "Demonstrate the desired pattern", "Train the model", "Test the API"], "Demonstrate the desired pattern", "Examples show the model exactly what you expect."),
                    ("Difference between zero-shot and few-shot?", ["Speed", "Few-shot includes examples", "Cost", "Model size"], "Few-shot includes examples", "Few-shot adds demonstration examples to guide the model."),
                    ("When is few-shot better than zero-shot?", ["Always", "When the task pattern is hard to describe", "Never", "For simple tasks"], "When the task pattern is hard to describe", "Examples can communicate patterns better than instructions alone."),
                ],
                [
                    ("What format should few-shot examples follow?", ["Random format", "Consistent input-output format", "Different formats each time", "No format needed"], "Consistent input-output format", "Consistency helps the model recognize and follow the pattern."),
                    ("What goes after the examples?", ["Nothing", "The actual input to process", "More examples", "Instructions again"], "The actual input to process", "After showing examples, you present the real input for processing."),
                    ("Should examples be labeled?", ["No", "Yes, with clear input-output markers", "Sometimes", "Only for code"], "Yes, with clear input-output markers", "Labels help the model understand the structure."),
                    ("How to separate examples?", ["No separation needed", "With consistent delimiters", "Random spacing", "Using colors"], "With consistent delimiters", "Clear separation helps the model parse individual examples."),
                ],
                [
                    ("When is few-shot most powerful?", ["All tasks equally", "Classification and formatting", "Image tasks", "Audio tasks"], "Classification and formatting", "Few-shot excels when demonstrating categories or output formats."),
                    ("Can few-shot teach domain terminology?", ["No", "Yes, through examples", "Only with fine-tuning", "Only for English"], "Yes, through examples", "Examples can demonstrate domain-specific language usage."),
                    ("Few-shot for sentiment analysis?", ["Not useful", "Very effective with labeled examples", "Only for English", "Requires fine-tuning"], "Very effective with labeled examples", "Showing positive/negative examples guides classification."),
                    ("What limits few-shot prompting?", ["Nothing", "Context window size", "Model type", "Time of day"], "Context window size", "More examples consume more tokens from the context window."),
                ],
            ],
        },
        # Lesson 8: Choosing Effective Examples
        {
            "sections": [
                ("Example Quality", "Quality matters more than quantity. Choose diverse examples that cover different scenarios and edge cases."),
                ("Consistency is Key", "Keep formatting consistent across all examples. Inconsistent examples confuse the model."),
                ("Ordering Strategy", "Order examples from simple to complex. Place the most relevant example closest to the actual task."),
            ],
            "quizzes": [
                [
                    ("What matters more in examples?", ["Quantity", "Quality and diversity", "Length", "Complexity"], "Quality and diversity", "A few diverse, high-quality examples beat many similar ones."),
                    ("Why include diverse examples?", ["To fill space", "Cover different scenarios and edge cases", "Look professional", "Use more tokens"], "Cover different scenarios and edge cases", "Diversity helps the model handle various inputs correctly."),
                    ("What is an edge case example?", ["Typical input", "Unusual or boundary input", "The longest input", "The shortest input"], "Unusual or boundary input", "Edge cases test how the model handles atypical scenarios."),
                    ("How many examples are usually enough?", ["1", "3-5 well-chosen ones", "20+", "100+"], "3-5 well-chosen ones", "A small set of diverse examples typically provides good coverage."),
                ],
                [
                    ("Why is consistency important in examples?", ["Saves tokens", "Prevents model confusion", "Looks better", "Required by API"], "Prevents model confusion", "Inconsistent formatting makes it hard for the model to learn the pattern."),
                    ("What should be consistent across examples?", ["Content", "Format, labels, and structure", "Length only", "Difficulty only"], "Format, labels, and structure", "All structural elements should follow the same pattern."),
                    ("What happens with inconsistent examples?", ["Better creativity", "Unpredictable output format", "Faster processing", "No effect"], "Unpredictable output format", "The model may not know which format to follow."),
                    ("Should example length vary?", ["Yes widely", "Content can vary but format should be consistent", "All same length", "Longer is better"], "Content can vary but format should be consistent", "Content diversity is good but structural consistency is key."),
                ],
                [
                    ("How should examples be ordered?", ["Random", "Simple to complex", "Complex to simple", "Alphabetically"], "Simple to complex", "Building from simple to complex helps the model understand progressively."),
                    ("Where to place the most relevant example?", ["First", "Closest to the actual task (last)", "Middle", "Does not matter"], "Closest to the actual task (last)", "Recency bias means the model pays more attention to nearby examples."),
                    ("What is recency bias in LLMs?", ["Preference for recent news", "More attention to tokens near the end", "Faster with recent models", "Newer is better"], "More attention to tokens near the end", "Models tend to weight recent context more heavily."),
                    ("Should you include negative examples?", ["Never", "Yes, to show what NOT to do", "Only for errors", "Only for testing"], "Yes, to show what NOT to do", "Negative examples help define boundaries of acceptable output."),
                ],
            ],
        },
        # Lesson 9: Few-shot Patterns for Different Tasks
        {
            "sections": [
                ("Classification Pattern", "Show labeled examples of each category. Text leads to Category label. Include examples of each category you want to classify into."),
                ("Extraction Pattern", "Demonstrate pulling structured data from unstructured text. Show the input text and the extracted key-value data."),
                ("Transformation Pattern", "Show input-output transformations like style changes, format conversions, or language translations."),
            ],
            "quizzes": [
                [
                    ("What is the classification pattern?", ["Sorting data", "Assigning labels to text", "Counting words", "Translating"], "Assigning labels to text", "Classification maps input text to predefined categories."),
                    ("How many categories should examples cover?", ["One", "All categories you want to use", "Random number", "As few as possible"], "All categories you want to use", "Each category needs at least one example for the model to learn."),
                    ("What makes a good classification example?", ["Long text", "Clear text with obvious category label", "Ambiguous text", "No label"], "Clear text with obvious category label", "Unambiguous examples help the model learn category boundaries."),
                    ("Can few-shot classify into custom categories?", ["No", "Yes, by defining them in examples", "Only standard categories", "Requires fine-tuning"], "Yes, by defining them in examples", "You can define any categories through your examples."),
                ],
                [
                    ("What is the extraction pattern?", ["Removing text", "Pulling structured data from text", "Summarizing", "Generating"], "Pulling structured data from text", "Extraction identifies and structures specific information from text."),
                    ("What format works well for extraction?", ["Paragraph", "Key-value pairs or JSON", "Single word", "Bullet points"], "Key-value pairs or JSON", "Structured formats make extracted data easy to parse."),
                    ("What to show in extraction examples?", ["Just the output", "Input text AND extracted data", "Only the fields", "Random data"], "Input text AND extracted data", "Both sides help the model learn what to extract and how."),
                    ("Can extraction handle nested data?", ["No", "Yes, with clear structure in examples", "Only flat data", "Requires special models"], "Yes, with clear structure in examples", "Examples can demonstrate nested JSON or hierarchical extraction."),
                ],
                [
                    ("What is the transformation pattern?", ["Deleting content", "Converting format or style", "Compressing", "Encrypting"], "Converting format or style", "Transformation changes text from one form to another."),
                    ("Example of transformation task?", ["Classification", "Rewriting formal text as casual", "Counting words", "Data storage"], "Rewriting formal text as casual", "Style transfer is a common transformation task."),
                    ("Key to good transformation examples?", ["Same input and output", "Clear before and after pairs", "Only showing output", "No structure needed"], "Clear before and after pairs", "Pairs demonstrate exactly what changes and what stays."),
                    ("Can transformations chain together?", ["No", "Yes, by showing multi-step examples", "Only two steps", "Requires multiple calls"], "Yes, by showing multi-step examples", "Examples can demonstrate sequential transformations."),
                ],
            ],
        },
        # Lesson 10: Iterative Prompt Refinement
        {
            "sections": [
                ("The Optimization Loop", "Write initial prompt, test with various inputs, analyze failures, refine, and repeat. Track versions of your prompts."),
                ("Identifying Weaknesses", "Look for inconsistencies, format violations, missed requirements, or hallucinations in outputs."),
                ("Metrics to Track", "Track accuracy, consistency across inputs, format adherence, and response relevance. Document improvements."),
            ],
            "quizzes": [
                [
                    ("What is the first step of prompt optimization?", ["Deploy", "Write an initial prompt", "Analyze results", "Refine"], "Write an initial prompt", "Start with your best attempt and iterate from there."),
                    ("Why track prompt versions?", ["For fun", "To understand what improvements work", "Required by API", "To increase cost"], "To understand what improvements work", "Version tracking shows which changes helped or hurt."),
                    ("How many test inputs should you use?", ["1", "Multiple diverse inputs", "Hundreds", "None"], "Multiple diverse inputs", "Diverse inputs reveal how the prompt handles different scenarios."),
                    ("When should you stop iterating?", ["After one try", "When outputs consistently meet requirements", "Never", "After 10 versions"], "When outputs consistently meet requirements", "Stop when the prompt reliably produces good results."),
                ],
                [
                    ("What to look for in outputs?", ["Word count only", "Inconsistencies and failures", "Spelling errors", "Token usage"], "Inconsistencies and failures", "Focus on where the prompt fails to produce correct output."),
                    ("What is a format violation?", ["Bad grammar", "Output not matching specified structure", "Too many tokens", "Slow response"], "Output not matching specified structure", "When the model ignores format requirements like JSON or bullet points."),
                    ("How to fix hallucinations?", ["Ignore them", "Add constraints and verification steps", "Use bigger model", "Lower temperature only"], "Add constraints and verification steps", "Constraints and explicit instructions to not make things up help."),
                    ("What is a prompt failure pattern?", ["Consistent error across similar inputs", "One-time mistake", "Spelling error", "Slow response"], "Consistent error across similar inputs", "Repeated failures indicate a systematic prompt weakness."),
                ],
                [
                    ("What metrics matter most?", ["Speed", "Accuracy and consistency", "Cost", "Model size"], "Accuracy and consistency", "The output must be correct and reliable across inputs."),
                    ("How to measure consistency?", ["One test", "Run same prompt multiple times", "Check grammar", "Count tokens"], "Run same prompt multiple times", "Multiple runs reveal how stable the output is."),
                    ("What is format adherence?", ["Following instructions", "Output matching the specified format exactly", "Using templates", "Correct spelling"], "Output matching the specified format exactly", "The output should match your format requirements precisely."),
                    ("Why document improvements?", ["Busywork", "Learn what techniques work for future prompts", "Required", "For auditing"], "Learn what techniques work for future prompts", "Documentation builds prompt engineering expertise over time."),
                ],
            ],
        },
        # Lesson 11: Temperature and Parameter Tuning
        {
            "sections": [
                ("Temperature Explained", "Temperature (0.0-2.0) controls randomness. 0.0 is deterministic, 0.7 is balanced, 1.5+ is highly creative."),
                ("Other Key Parameters", "Top-p controls diversity, max tokens limits length, frequency penalty reduces repetition, presence penalty encourages new topics."),
                ("Choosing the Right Settings", "Use low temperature (0.0-0.3) for factual tasks, medium (0.5-0.7) for balanced output, high (1.0+) for creative writing."),
            ],
            "quizzes": [
                [
                    ("What does temperature control?", ["Speed", "Randomness", "Quality", "Token count"], "Randomness", "Temperature determines how random or deterministic the output is."),
                    ("What temperature gives deterministic output?", ["2.0", "1.0", "0.0", "0.5"], "0.0", "Temperature 0.0 always picks the most likely token."),
                    ("What happens at high temperature?", ["Slower output", "More creative and random output", "Better accuracy", "Fewer tokens"], "More creative and random output", "High temperature increases randomness and creativity."),
                    ("What is a balanced temperature?", ["0.0", "0.5-0.7", "2.0", "5.0"], "0.5-0.7", "This range balances creativity with coherence."),
                ],
                [
                    ("What does top-p control?", ["Temperature", "Token diversity in selection", "Model size", "Speed"], "Token diversity in selection", "Top-p (nucleus sampling) limits the token pool to the most probable."),
                    ("What does max tokens limit?", ["Input only", "Output length", "Model parameters", "Temperature"], "Output length", "Max tokens caps how long the generated response can be."),
                    ("What does frequency penalty do?", ["Increases speed", "Reduces word repetition", "Adds tokens", "Changes model"], "Reduces word repetition", "It penalizes tokens that appear frequently in the output."),
                    ("What does presence penalty encourage?", ["Repetition", "Exploring new topics", "Shorter output", "Faster response"], "Exploring new topics", "Presence penalty makes the model less likely to repeat topics."),
                ],
                [
                    ("Best temperature for factual tasks?", ["0.0-0.3", "0.7", "1.5", "2.0"], "0.0-0.3", "Low temperature ensures accurate, consistent factual output."),
                    ("Best temperature for creative writing?", ["0.0", "0.3", "0.8-1.2", "0.1"], "0.8-1.2", "Higher temperature enables more creative and varied output."),
                    ("Should you tune multiple parameters at once?", ["Yes all at once", "No, change one at a time", "Only temperature matters", "Parameters do not matter"], "No, change one at a time", "Changing one parameter at a time helps understand each effect."),
                    ("Best settings for code generation?", ["High temperature", "Low temperature with low top-p", "Maximum randomness", "No parameters needed"], "Low temperature with low top-p", "Code requires precision, so lower randomness is better."),
                ],
            ],
        },
        # Lesson 12: Common Prompt Anti-patterns
        {
            "sections": [
                ("Vague Instructions", "Avoid ambiguous or generic instructions like do something interesting. Be specific about what you want the model to produce."),
                ("Conflicting Requirements", "Do not give contradictory instructions like be concise but very detailed. Clarify priorities and resolve conflicts."),
                ("Missing Context", "Do not assume the AI knows your domain or background. Provide necessary context and define domain-specific terms in the prompt."),
            ],
            "quizzes": [
                [
                    ("What is a prompt anti-pattern?", ["Best practice", "Common mistake to avoid", "Required format", "Advanced technique"], "Common mistake to avoid", "Anti-patterns are common mistakes that lead to poor results."),
                    ("Why are vague instructions bad?", ["They save tokens", "They produce unpredictable results", "They are faster", "They are easier"], "They produce unpredictable results", "Vagueness gives the model too much freedom to interpret."),
                    ("Example of vague instruction?", ["List 5 items about X", "Do something interesting", "Summarize in 100 words", "Translate to Spanish"], "Do something interesting", "This gives no clear direction for what the model should produce."),
                    ("How to fix a vague prompt?", ["Make it shorter", "Add specific details and constraints", "Remove all context", "Use simpler words"], "Add specific details and constraints", "Specificity guides the model toward your desired output."),
                ],
                [
                    ("What is a conflicting requirement?", ["Two clear instructions", "Contradictory demands in one prompt", "Multiple tasks", "Long prompts"], "Contradictory demands in one prompt", "Telling the model to be both brief and comprehensive creates conflict."),
                    ("How do LLMs handle conflicts?", ["Perfectly", "May produce confused or inconsistent output", "Ignore one instruction", "Ask for clarification"], "May produce confused or inconsistent output", "Models try to satisfy all instructions, leading to poor results."),
                    ("How to resolve conflicting requirements?", ["Remove all constraints", "Prioritize and clarify which matters more", "Add more instructions", "Use higher temperature"], "Prioritize and clarify which matters more", "Clear priorities help the model make appropriate tradeoffs."),
                    ("Example of conflicting prompt?", ["Write a summary", "Be extremely brief AND include every detail", "List 5 items", "Translate this text"], "Be extremely brief AND include every detail", "Brevity and comprehensiveness are fundamentally at odds."),
                ],
                [
                    ("Why is missing context problematic?", ["It saves tokens", "Model cannot access your specific knowledge", "It is faster", "Context is optional"], "Model cannot access your specific knowledge", "The model has no way to know your specific domain or situation."),
                    ("What context should you provide?", ["Everything you know", "Relevant background and domain terms", "Nothing", "Only the question"], "Relevant background and domain terms", "Provide enough context for the model to understand the task."),
                    ("Should you define acronyms?", ["No, models know all acronyms", "Yes, define domain-specific acronyms", "Only common ones", "Never use acronyms"], "Yes, define domain-specific acronyms", "Domain-specific acronyms may be ambiguous without definition."),
                    ("What is a good practice for context?", ["Assume shared knowledge", "Include a brief context paragraph", "Skip context to save tokens", "Only use technical terms"], "Include a brief context paragraph", "A short context section helps orient the model for the task."),
                ],
            ],
        },
    ]
    
    for lesson_idx, data in enumerate(_SECTIONS_DATA):
        lesson = lessons[lesson_idx]
        sections_objs = []
        for sec_order, (sec_title, sec_content) in enumerate(data["sections"], 1):
            sec = LessonSection(
                lesson_id=lesson.id,
                title=sec_title,
                content=sec_content,
                order=sec_order,
            )
            sections_objs.append(sec)
        db.add_all(sections_objs)
        db.flush()
        
        for sec_idx, section in enumerate(sections_objs):
            quizzes_for_section = data["quizzes"][sec_idx]
            quiz_objs = []
            for q_order, (question, options, answer, explanation) in enumerate(quizzes_for_section, 1):
                quiz_objs.append(SectionQuiz(
                    section_id=section.id,
                    question=question,
                    options=options,
                    correct_answer=answer,
                    explanation=explanation,
                    order=q_order,
                ))
            db.add_all(quiz_objs)
