"""Seed data script for the Prompt Engineering LMS."""
import logging

from sqlalchemy.orm import Session

from app.db.database import SessionLocal, engine, Base
from app.models.models import (
    User,
    RoleEnum,
    Basket,
    Module,
    Lesson,
    Exercise,
    Quiz,
    Lab,
    Assignment,
)
from app.services.auth import hash_password

logger = logging.getLogger(__name__)


def seed_database():
    """Populate the database with initial seed data."""
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    try:
        # Check if data already exists
        if db.query(User).first():
            logger.info("Database already seeded. Skipping.")
            return

        logger.info("Seeding database...")

        # ── Create Admin User ─────────────────────────────────────────────
        admin = User(
            email="admin@prompteng.edu",
            username="admin",
            hashed_password=hash_password("admin123"),
            full_name="Platform Admin",
            role=RoleEnum.ADMIN,
        )
        db.add(admin)

        # ── Create Demo Student ───────────────────────────────────────────
        student = User(
            email="student@prompteng.edu",
            username="student",
            hashed_password=hash_password("student123"),
            full_name="Demo Student",
            role=RoleEnum.STUDENT,
        )
        db.add(student)
        db.flush()

        # ── Create Baskets ───────────────────────────────────────────────
        basket1 = Basket(
            title="Basic Prompt Engineering",
            description="Foundation course covering the basics of prompt engineering with LLMs. Learn how to write effective prompts, understand LLM behavior, and apply fundamental techniques.",
            credits=8,
            order=1,
        )
        basket2 = Basket(
            title="Intermediate Prompt Engineering",
            description="Advanced techniques including chain-of-thought, multi-step prompting, and domain-specific prompt design patterns.",
            credits=8,
            order=2,
        )
        basket3 = Basket(
            title="Advanced Prompt Engineering",
            description="Expert-level prompt engineering covering autonomous agents, complex workflow design, and production-grade prompt systems.",
            credits=8,
            order=3,
        )
        db.add_all([basket1, basket2, basket3])
        db.flush()

        # ── Basket 1: Basic Prompt Engineering ────────────────────────────

        # Module 1: Introduction to LLMs
        mod1 = Module(
            basket_id=basket1.id,
            title="Introduction to LLMs",
            description="Understand the fundamentals of Large Language Models and how they process prompts.",
            order=1,
        )
        # Module 2: Prompt Fundamentals
        mod2 = Module(
            basket_id=basket1.id,
            title="Prompt Fundamentals",
            description="Learn the core principles of writing effective prompts for AI systems.",
            order=2,
        )
        # Module 3: Few-shot Prompting
        mod3 = Module(
            basket_id=basket1.id,
            title="Few-shot Prompting",
            description="Master the technique of providing examples to guide AI responses.",
            order=3,
        )
        # Module 4: Prompt Optimization
        mod4 = Module(
            basket_id=basket1.id,
            title="Prompt Optimization",
            description="Learn systematic approaches to improve and optimize your prompts.",
            order=4,
        )
        db.add_all([mod1, mod2, mod3, mod4])
        db.flush()

        # ── Lessons for Module 1: Introduction to LLMs ───────────────────
        lessons_mod1 = [
            Lesson(
                module_id=mod1.id,
                title="What are Large Language Models?",
                content=(
                    "Large Language Models (LLMs) are AI systems trained on vast amounts of text data. "
                    "They can understand and generate human-like text based on the input they receive.\n\n"
                    "Key concepts:\n"
                    "- **Tokens**: LLMs process text as tokens (words or word pieces)\n"
                    "- **Context Window**: The amount of text an LLM can consider at once\n"
                    "- **Temperature**: Controls randomness in responses\n"
                    "- **Completion**: The text generated by the model"
                ),
                transcript="In this lesson, we explore what large language models are and how they work...",
                notes="LLMs are trained on billions of parameters using transformer architecture.",
                video_url="https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1280&h=720&fit=crop&q=80",
                order=1,
                duration_minutes=15,
            ),
            Lesson(
                module_id=mod1.id,
                title="How LLMs Process Prompts",
                content=(
                    "Understanding how LLMs process your input is crucial for effective prompt engineering.\n\n"
                    "The processing pipeline:\n"
                    "1. **Tokenization**: Your text is split into tokens\n"
                    "2. **Encoding**: Tokens are converted to numerical representations\n"
                    "3. **Attention**: The model weighs the importance of each token\n"
                    "4. **Generation**: Output tokens are produced one at a time\n\n"
                    "This is why prompt structure matters - the model's attention mechanism "
                    "determines what parts of your prompt influence the output most."
                ),
                transcript="Let's dive into the internal workings of how an LLM processes your prompts...",
                notes="Attention mechanism is the key innovation behind transformer models.",
                video_url="https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1280&h=720&fit=crop&q=80",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod1.id,
                title="Common LLM Capabilities and Limitations",
                content=(
                    "LLMs have impressive capabilities but also important limitations.\n\n"
                    "**Capabilities:**\n"
                    "- Text generation and completion\n"
                    "- Summarization and extraction\n"
                    "- Translation and paraphrasing\n"
                    "- Code generation\n"
                    "- Reasoning and analysis\n\n"
                    "**Limitations:**\n"
                    "- Can hallucinate (generate false information)\n"
                    "- Knowledge cutoff dates\n"
                    "- Token limit constraints\n"
                    "- May not follow complex instructions consistently"
                ),
                transcript="In this lesson, we'll explore what LLMs can and cannot do...",
                notes="Always verify critical information from LLM outputs.",
                video_url="https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1280&h=720&fit=crop&q=80",
                order=3,
                duration_minutes=18,
            ),
        ]
        db.add_all(lessons_mod1)
        db.flush()

        # ── Lessons for Module 2: Prompt Fundamentals ─────────────────────
        lessons_mod2 = [
            Lesson(
                module_id=mod2.id,
                title="Anatomy of a Good Prompt",
                content=(
                    "A well-structured prompt has several key components:\n\n"
                    "1. **Role/Context**: Define who the AI should be\n"
                    "2. **Task**: Clearly state what you want done\n"
                    "3. **Constraints**: Set boundaries and requirements\n"
                    "4. **Output Format**: Specify how the response should be structured\n"
                    "5. **Examples**: Provide sample inputs and outputs\n\n"
                    "Example:\n"
                    "```\n"
                    "You are a professional copywriter.\n"
                    "Write a product description for a wireless mouse.\n"
                    "Keep it under 100 words.\n"
                    "Use bullet points for features.\n"
                    "```"
                ),
                transcript="Let's learn the fundamental building blocks of an effective prompt...",
                notes="Always start with the role and end with the desired output format.",
                video_url="https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1280&h=720&fit=crop&q=80",
                order=1,
                duration_minutes=25,
            ),
            Lesson(
                module_id=mod2.id,
                title="Zero-shot Prompting",
                content=(
                    "Zero-shot prompting is when you ask the AI to perform a task without providing examples.\n\n"
                    "This relies on the model's pre-trained knowledge.\n\n"
                    "**Example:**\n"
                    "```\n"
                    "Classify the following text as positive, negative, or neutral:\n"
                    "'The weather today is absolutely beautiful!'\n"
                    "```\n\n"
                    "**Tips for better zero-shot prompts:**\n"
                    "- Be as specific as possible\n"
                    "- Use clear, unambiguous language\n"
                    "- Specify the exact output format you want"
                ),
                transcript="Zero-shot prompting is the simplest form of prompt engineering...",
                notes="Zero-shot works best for simple, well-defined tasks.",
                video_url="https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=1280&h=720&fit=crop&q=80",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod2.id,
                title="Instruction Clarity and Specificity",
                content=(
                    "The clarity of your instructions directly impacts the quality of AI output.\n\n"
                    "**Vague vs. Specific:**\n"
                    "- Vague: 'Tell me about Python'\n"
                    "- Specific: 'Explain the difference between lists and tuples in Python with code examples'\n\n"
                    "**Techniques for clarity:**\n"
                    "1. Use numbered steps for multi-part tasks\n"
                    "2. Define technical terms if needed\n"
                    "3. Specify the audience level\n"
                    "4. Set word/length constraints\n"
                    "5. Use delimiters to separate sections"
                ),
                transcript="Let's explore how to make your prompts crystal clear...",
                notes="Specificity reduces ambiguity and improves AI output quality.",
                video_url="https://images.unsplash.com/photo-1518770660439-4636190af475?w=1280&h=720&fit=crop&q=80",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod2)
        db.flush()

        # ── Lessons for Module 3: Few-shot Prompting ──────────────────────
        lessons_mod3 = [
            Lesson(
                module_id=mod3.id,
                title="Introduction to Few-shot Learning",
                content=(
                    "Few-shot prompting provides examples to guide the AI's behavior.\n\n"
                    "**Structure:**\n"
                    "```\n"
                    "Example 1:\n"
                    "Input: [example input]\n"
                    "Output: [example output]\n\n"
                    "Example 2:\n"
                    "Input: [example input]\n"
                    "Output: [example output]\n\n"
                    "Now do this:\n"
                    "Input: [your actual input]\n"
                    "Output:\n"
                    "```\n\n"
                    "Few-shot prompting is especially powerful for:\n"
                    "- Classification tasks\n"
                    "- Format standardization\n"
                    "- Domain-specific terminology"
                ),
                transcript="Few-shot learning is one of the most powerful techniques...",
                notes="Even 2-3 examples can dramatically improve output quality.",
                video_url="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1280&h=720&fit=crop&q=80",
                order=1,
                duration_minutes=25,
            ),
            Lesson(
                module_id=mod3.id,
                title="Choosing Effective Examples",
                content=(
                    "The quality and diversity of your examples matters more than quantity.\n\n"
                    "**Guidelines:**\n"
                    "1. Choose diverse examples that cover edge cases\n"
                    "2. Keep examples consistent in format\n"
                    "3. Include both simple and complex cases\n"
                    "4. Make sure examples are correct\n"
                    "5. Order examples from simple to complex\n\n"
                    "**Common mistakes:**\n"
                    "- Using too many similar examples\n"
                    "- Providing incorrect examples\n"
                    "- Inconsistent formatting between examples"
                ),
                transcript="Selecting the right examples is crucial for few-shot prompting...",
                notes="Quality over quantity - 3 diverse examples beat 10 similar ones.",
                video_url="https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1280&h=720&fit=crop&q=80",
                order=2,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod3.id,
                title="Few-shot Patterns for Different Tasks",
                content=(
                    "Different tasks benefit from different few-shot patterns.\n\n"
                    "**Classification Pattern:**\n"
                    "Text: 'Great product!' -> Sentiment: Positive\n"
                    "Text: 'Terrible service' -> Sentiment: Negative\n\n"
                    "**Extraction Pattern:**\n"
                    "Text: 'John is 30 years old' -> {name: 'John', age: 30}\n\n"
                    "**Transformation Pattern:**\n"
                    "Formal: 'I would like to...' -> Casual: 'I wanna...'\n\n"
                    "**Generation Pattern:**\n"
                    "Topic: 'AI' -> Title: '10 Ways AI is Changing Healthcare'"
                ),
                transcript="Let's explore specific few-shot patterns for common tasks...",
                notes="Match your example pattern to your specific task type.",
                video_url="https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1280&h=720&fit=crop&q=80",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod3)
        db.flush()

        # ── Lessons for Module 4: Prompt Optimization ─────────────────────
        lessons_mod4 = [
            Lesson(
                module_id=mod4.id,
                title="Iterative Prompt Refinement",
                content=(
                    "Prompt optimization is an iterative process.\n\n"
                    "**The Optimization Loop:**\n"
                    "1. Write initial prompt\n"
                    "2. Test with various inputs\n"
                    "3. Analyze output quality\n"
                    "4. Identify weaknesses\n"
                    "5. Refine the prompt\n"
                    "6. Repeat\n\n"
                    "**Metrics to track:**\n"
                    "- Accuracy of responses\n"
                    "- Consistency across inputs\n"
                    "- Adherence to format\n"
                    "- Response relevance"
                ),
                transcript="Let's learn how to systematically improve prompts...",
                notes="Keep a log of prompt versions and their results.",
                video_url="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1280&h=720&fit=crop&q=80",
                order=1,
                duration_minutes=20,
            ),
            Lesson(
                module_id=mod4.id,
                title="Temperature and Parameter Tuning",
                content=(
                    "Model parameters significantly affect output quality.\n\n"
                    "**Temperature (0.0 - 2.0):**\n"
                    "- 0.0: Deterministic, focused responses\n"
                    "- 0.7: Balanced creativity and accuracy\n"
                    "- 1.5+: Highly creative, less predictable\n\n"
                    "**Other parameters:**\n"
                    "- **Top-p**: Controls diversity of token selection\n"
                    "- **Max tokens**: Limits response length\n"
                    "- **Frequency penalty**: Reduces repetition\n"
                    "- **Presence penalty**: Encourages topic diversity"
                ),
                transcript="Understanding model parameters helps you fine-tune outputs...",
                notes="Start with temperature 0.7 and adjust based on task needs.",
                video_url="https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=1280&h=720&fit=crop&q=80",
                order=2,
                duration_minutes=18,
            ),
            Lesson(
                module_id=mod4.id,
                title="Common Prompt Anti-patterns",
                content=(
                    "Avoid these common mistakes in prompt engineering.\n\n"
                    "**Anti-patterns:**\n"
                    "1. **Vague instructions**: 'Do something interesting with this data'\n"
                    "2. **Conflicting requirements**: 'Be concise but detailed'\n"
                    "3. **Missing context**: Assuming the AI knows your domain\n"
                    "4. **Over-constraining**: Too many rules that conflict\n"
                    "5. **Prompt injection vulnerability**: Not sanitizing user inputs\n\n"
                    "**Best practices:**\n"
                    "- Test prompts with edge cases\n"
                    "- Version control your prompts\n"
                    "- Document what works and what doesn't"
                ),
                transcript="Let's identify and fix common prompt engineering mistakes...",
                notes="The best prompt engineers learn from their failures.",
                video_url="https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1280&h=720&fit=crop&q=80",
                order=3,
                duration_minutes=22,
            ),
        ]
        db.add_all(lessons_mod4)
        db.flush()

        # ── Create Exercises ──────────────────────────────────────────────
        exercises = [
            Exercise(
                lesson_id=lessons_mod2[0].id,
                title="Write a Role-Based Prompt",
                description="Create a prompt that assigns a specific role to the AI and asks it to complete a task.",
                prompt_template="You are a [role]. [task]. [constraints]. [output format].",
                expected_output="A well-structured prompt with role, task, constraints, and output format.",
                hints="Think about what expert would be best suited for the task.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod2[1].id,
                title="Zero-shot Classification",
                description="Write a zero-shot prompt to classify customer reviews as positive, negative, or neutral.",
                prompt_template="Classify the following customer review as positive, negative, or neutral: '[review text]'",
                expected_output="The classification label with a brief explanation.",
                hints="Be specific about the classification categories and output format.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod3[0].id,
                title="Few-shot Sentiment Analysis",
                description="Create a few-shot prompt for sentiment analysis with at least 3 examples.",
                prompt_template="Classify the sentiment:\nExample 1: 'Love it!' -> Positive\nExample 2: 'Worst ever' -> Negative\nNow classify: '[text]'",
                expected_output="Correct sentiment classification following the example format.",
                hints="Use diverse examples covering different expressions.",
                order=1,
            ),
            Exercise(
                lesson_id=lessons_mod4[0].id,
                title="Prompt Iteration Challenge",
                description="Start with a basic prompt and iterate 3 times to improve it, documenting changes.",
                prompt_template="Version 1: [basic prompt]\nVersion 2: [improved prompt]\nVersion 3: [optimized prompt]",
                expected_output="Three versions showing clear improvement in clarity and specificity.",
                hints="Focus on one improvement dimension per iteration.",
                order=1,
            ),
        ]
        db.add_all(exercises)

        # ── Create Quizzes ────────────────────────────────────────────────
        quizzes = [
            Quiz(
                lesson_id=lessons_mod1[0].id,
                question="What is the primary input to a Large Language Model?",
                options=["Images", "Tokens (text)", "Audio files", "Binary data"],
                correct_answer="Tokens (text)",
                explanation="LLMs process text as tokens, which are words or sub-word pieces.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod1[1].id,
                question="What mechanism allows LLMs to weigh the importance of different tokens?",
                options=["Convolution", "Attention", "Pooling", "Dropout"],
                correct_answer="Attention",
                explanation="The attention mechanism is the key innovation in transformer models.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod2[0].id,
                question="Which component should typically come FIRST in a well-structured prompt?",
                options=["Output format", "Examples", "Role/Context", "Constraints"],
                correct_answer="Role/Context",
                explanation="Setting the role/context first helps frame the entire interaction.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod3[0].id,
                question="How many examples are typically needed for effective few-shot prompting?",
                options=["1", "2-5", "10-20", "50+"],
                correct_answer="2-5",
                explanation="Usually 2-5 well-chosen examples are sufficient for most tasks.",
                order=1,
            ),
            Quiz(
                lesson_id=lessons_mod4[1].id,
                question="What temperature value would you use for a factual Q&A task?",
                options=["0.0 - 0.3", "0.5 - 0.7", "1.0 - 1.5", "2.0"],
                correct_answer="0.0 - 0.3",
                explanation="Low temperature produces more deterministic, focused responses suitable for factual tasks.",
                order=1,
            ),
        ]
        db.add_all(quizzes)

        # ── Create Labs ───────────────────────────────────────────────────
        labs = [
            Lab(
                module_id=mod1.id,
                title="Build a Chatbot Prompt",
                description="Design a system prompt for a customer service chatbot.",
                instructions=(
                    "1. Define the chatbot's personality and role\n"
                    "2. Set boundaries for what the chatbot can and cannot discuss\n"
                    "3. Include example interactions\n"
                    "4. Add safety guidelines\n"
                    "5. Test with various customer queries"
                ),
                starter_prompt="You are a helpful customer service assistant for [company]...",
                expected_output="A complete system prompt that handles various customer scenarios.",
                max_score=100,
            ),
            Lab(
                module_id=mod2.id,
                title="Structured JSON Extraction",
                description="Create a prompt that extracts structured data from unstructured text.",
                instructions=(
                    "1. Write a prompt that takes a paragraph of text\n"
                    "2. Extract key entities (names, dates, locations, amounts)\n"
                    "3. Output in valid JSON format\n"
                    "4. Handle edge cases (missing data, ambiguous references)\n"
                    "5. Include few-shot examples"
                ),
                starter_prompt="Extract the following information from the text and return as JSON...",
                expected_output="A JSON extraction prompt that works reliably across different inputs.",
                max_score=100,
            ),
            Lab(
                module_id=mod3.id,
                title="Multi-step Prompt Chain",
                description="Design a chain of prompts that work together to solve a complex task.",
                instructions=(
                    "1. Break down a complex task into 3-4 steps\n"
                    "2. Design a prompt for each step\n"
                    "3. Define how output from one step feeds into the next\n"
                    "4. Handle errors between steps\n"
                    "5. Test the complete chain"
                ),
                starter_prompt="Step 1: Analyze the text...\nStep 2: Based on the analysis...",
                expected_output="A working chain of prompts that solves a multi-step problem.",
                max_score=100,
            ),
            Lab(
                module_id=mod4.id,
                title="AI Assistant Workflow",
                description="Build a complete AI assistant workflow for a specific domain.",
                instructions=(
                    "1. Choose a domain (e.g., healthcare, legal, education)\n"
                    "2. Design the system prompt\n"
                    "3. Create prompt templates for common tasks\n"
                    "4. Implement safety and guardrails\n"
                    "5. Create a testing suite with diverse inputs\n"
                    "6. Document the workflow"
                ),
                starter_prompt="You are an AI assistant specializing in [domain]...",
                expected_output="A production-ready AI assistant workflow with documentation.",
                max_score=100,
            ),
        ]
        db.add_all(labs)

        # ── Create Assignments ────────────────────────────────────────────
        assignments = [
            Assignment(
                module_id=mod1.id,
                title="LLM Exploration Report",
                description="Explore different LLMs and write a comparison report.",
                instructions=(
                    "1. Test the same prompt on at least 2 different LLMs\n"
                    "2. Compare the responses for quality, accuracy, and style\n"
                    "3. Document your findings with examples\n"
                    "4. Recommend which LLM works best for specific task types"
                ),
                rubric={
                    "prompt_quality": 25,
                    "comparison_depth": 25,
                    "examples": 25,
                    "recommendations": 25,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod2.id,
                title="Prompt Design Portfolio",
                description="Create a portfolio of 5 well-designed prompts for different tasks.",
                instructions=(
                    "1. Write prompts for: summarization, extraction, classification, generation, and analysis\n"
                    "2. Each prompt must include role, task, constraints, and output format\n"
                    "3. Test each prompt and include the AI output\n"
                    "4. Write a brief explanation of your design choices"
                ),
                rubric={
                    "prompt_variety": 20,
                    "prompt_quality": 30,
                    "testing": 25,
                    "explanation": 25,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod3.id,
                title="Few-shot Prompting Challenge",
                description="Solve 3 complex tasks using few-shot prompting techniques.",
                instructions=(
                    "1. Design few-shot prompts for:\n"
                    "   a. Named Entity Recognition\n"
                    "   b. Text style transfer\n"
                    "   c. Data format conversion\n"
                    "2. Include 3-5 examples per prompt\n"
                    "3. Test with at least 5 different inputs each\n"
                    "4. Report accuracy and analyze failures"
                ),
                rubric={
                    "example_quality": 30,
                    "prompt_design": 25,
                    "testing_thoroughness": 25,
                    "analysis": 20,
                },
                max_score=100,
                due_hours=168,
            ),
            Assignment(
                module_id=mod4.id,
                title="Prompt Optimization Case Study",
                description="Document the optimization journey of a complex prompt.",
                instructions=(
                    "1. Choose a complex real-world task\n"
                    "2. Start with a naive prompt (Version 1)\n"
                    "3. Iterate at least 5 times\n"
                    "4. Document each version with:\n"
                    "   - The prompt text\n"
                    "   - What changed and why\n"
                    "   - Test results\n"
                    "   - Score improvements\n"
                    "5. Write a conclusion about optimization strategies"
                ),
                rubric={
                    "iteration_quality": 25,
                    "documentation": 25,
                    "improvement_shown": 25,
                    "conclusion": 25,
                },
                max_score=100,
                due_hours=336,
            ),
        ]
        db.add_all(assignments)

        db.commit()
        logger.info("Database seeded successfully!")

    except Exception as e:
        db.rollback()
        logger.error(f"Seeding failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
